### ISSUE TITLE
Could you please share the dataset Baby Chillanto

### ISSUE THREAD

**Issue by Ryuk17** [ThomasAbdAlKarim/CryClass#1]
Thanks for your sharing your code, i want to run your code but i cannot get the dataset Baby Chillanto whose webpage is not available.  So could you please share the dataset Baby Chillanto?

**Comment by ThomasAbdAlKarim** [comment]
> Thanks for your sharing your code, i want to run your code but i cannot get the dataset Baby Chillanto whose webpage is not available.  So could you please share the dataset Baby Chillanto?

All the data is in the model file in the repository including the chillanto dataset

**Comment by Ryuk17** [comment]
> > Thanks for your sharing your code, i want to run your code but i cannot get the dataset Baby Chillanto whose webpage is not available.  So could you please share the dataset Baby Chillanto?
> 
> All the data is in the model file in the repository including the chillanto dataset

Thanks, the size is smaller than i expected.
