### ISSUE TITLE
Data label

### ISSUE THREAD

**Issue by dinhvany** [ThomasAbdAlKarim/CryClass#2]
Thank you for sharing the code and dataset. I see the data label session, at the first loop, I don't understand, can you explain me?

// lable for hungry
for i in range(len(Audio_UnCom) + 100):
    Data.append(Save_MFCC(Audio_Hungry[i],Sr))
    Y.append(0) 
// I think it should: 
for Audio_File in Audio_Hungry:
    Data.append(Save_MFCC(Audio_File,Sr))
    Y.append(0)

Thank you in advance.

**Comment by ThomasAbdAlKarim** [comment]
It is to have a more balanced dataset, we have a very large hungry dataset but a small uncomfortable one, by only taking uncom +100 we keep the dataset somewhat balanced

**Comment by ThomasAbdAlKarim** [comment]
But of course if you want you can load them all but it will be biased a bit towards hungry

**Comment by dinhvany** [comment]
Thank you for explaining this issue to me.  The dataset that you use in this project is self_recorded? Was it cited in the paper?

**Comment by ThomasAbdAlKarim** [comment]
It is a mix of I would say around 50% old dataset i found online 30% self recorded 20% data augmentation

**Comment by dinhvany** [comment]
I am founding datasets on websites like Baby Chillanto, SPLANN,.., but it is impossiple. Do you suggest me?

**Comment by ThomasAbdAlKarim** [comment]
My dataset contains these ones I did search everywhere I could find data a recommendation would maybe be YouTube videos download to mp3 and chop them
